### ISSUE TITLE
is that possible to remove _. at the beginning of the variable name

### ISSUE THREAD

**Issue by TonyFly3000** [machow/siuba#151]
Its a great package .I am so use to dplyr . I am looking package like it for a long time.

May I know is that possible to remove the _.  at beginning of the variable name 
Also can we use  %>% instead of  >>

**Comment by machow** [comment]
Thanks @TonyFly3000!

> is that possible to remove the _. at beginning of the variable name

We can't remove it completely, but there are some packages like https://github.com/has2k1/plydata that use a string, rather than the underscore. The underscore is how siuba knows it's a symbolic expression (that it might need to, e.g., convert to SQL).

> Also can we use %>% instead of >>

Unfortunately, this is not possible, since `%>%` is not a valid python operator ([list here](https://docs.python.org/3.4/library/operator.html#mapping-operators-to-functions)).

```
import ast
ast.parse("1 %>% 2")
```

Happy to fix anything / answer more questions
