### ISSUE TITLE
Using and/or to test multiple condition inside if_else fails

### ISSUE THREAD

**Issue by sahoosatish** [machow/siuba#429]
Hi,
     I am running the following code and it fails. I tried a lot of options and searched extensively within this repository but didn't find a solution. Please let me know if this is supported or if I am missing something.

comp >> mutate(gwi = if_else((_.gwi>0 and _.fyear<=2001), _.GWIE,_.gwi ))

fails with-
TypeError: Symbolic objects can not be converted to True/False, or used with these keywords: not, and, or.

Thanks

**Comment by machow** [comment]
Hey, there's a small section in the [filter docs](https://siuba.readthedocs.io/en/latest/api_table_core/01_filter.html#Filters-with-OR-conditions), but I'm hoping to finish new documentation by the end of month, with this kind of information much easier to find.

python data tools like pandas, numpy, and siuba use..

* `&` for and
* `|` for or

```
from siuba.data import mtcars
from siuba import _, mutate, if_else

(mtcars
    >> mutate(
        res = if_else((_.mpg > 20) & (_.cyl > 4),  "high mpg high cyl", "other")
    )
)
```

Note that--due to how python precedence works for these--be sure to put the left hand and right hand sides in parentheses! (e.g. `(_.mpg > 20) & (_.cyl > 4)`, rather than `_.mpg > 20 & _.cyl > 4`).

I often double check the operations in pandas, as a first troubleshooting step:

```
(mtcars.mpg > 20) & (mtcars.cyl > 4)
```

Hope this helps :)

**Comment by sahoosatish** [comment]
Thanks a lot, Michael. I appreciate your quick response.
I tried & earlier as well but I was using ((mtcars.mpg > 20) & (mtcars.cyl > 4))
The outer parenthesis was causing the issue then. This is surprising as in panda operations at least, I think outer ()  is recommended. In any case, I am relatively new to python and super new to siuba.
Thanks a lot. I appreciate your effort in creating and maintaining and extending the package.

**Comment by machow** [comment]
No problem! If you run into the problem again, and can reproduce it in this issue with the mtcars data, I'm happy to double check!

I think the outer () should be okay, but definitely feel free to reopen if you hit the issue again
